# Generated by Django 4.0.6 on 2022-08-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='classtaught',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='subject',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='rollno',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='section',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='stream',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='studclass',
            field=models.CharField(default='', max_length=10),
        ),
    ]
