# Generated by Django 4.0.6 on 2022-08-02 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_profile_delete_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
